### PR TITLE
🔧 Fix: Fresh profile first run crash

### PR DESCRIPTION
**Pull request by typhoonbro**
Bug fix for the game crashing when starting the first run of a fresh profile with zero unlocks.

### CODE REVIEW

**Comment by kjossul** [comment]
Still crashes for me on a blank savefile. I think a manual check on the `G.SETTINGS.tutorial_complete` flag is required.

**Comment by kjossul** [comment]
Actually, how do you properly reset the settings to replay the tutorial? Removing the save folders and settings.jkr seems to make my game crash independently on the mod being active or not, so there's nothing wrong with your code.

**Comment by typhoonbro** [comment]
> Actually, how do you properly reset the settings to replay the tutorial? Removing the save folders and settings.jkr seems to make my game crash independently on the mod being active or not, so there's nothing wrong with your code.

I actually change the profile on the main menu to a new one. The thing about the tutorial is that it triggers a render of an extra UI over the blind selection selection screen. So loading the mod and displaying an overlay over it shouldn't cause a crash.

**Comment by typhoonbro** [comment]
Maybe try a fresh install of the base game and the mod loader?

**Comment by typhoonbro** [comment]
In my testing, I realized that the crash was caused by a function that updates the profile for the cards unlocked. As the neow card was being treated as a joker card, the function was expecting a few arguments that the mod's code wasn't passing on, so it crashed as it trying to "unlock" the neow card for the profile.

**Comment by kjossul** [comment]
> In my testing, I realized that the crash was caused by a function that updates the profile for the cards unlocked. As the neow card was being treated as a joker card, the function was expecting a few arguments that the mod's code wasn't passing on, so it crashed as it trying to "unlock" the neow card for the profile.

Yeah I tried to switch to new profiles but I couldn't retrigger the tutorial, and I didn't experience crashes. Anyway, I did a blank install and now no more crashes, so we can merge! I still think there's some merit in just skipping the blessings if the user hasn't played the tutorial yet but it's such an edge case (who would install mods before having played the tutorial anyway?) but your changes are good for now 👍

**Pull request merged**
